version: "3.9"
services:
  backend:
    build: ./backend/
    image: skillforgebackend
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:12345678@database:5432/skillforge"
      PORT: 3000
      MAX_SESSION_TIME_IN_SEC: 1800
      PUBLIC_STORAGE_URL: "http://localhost:9000"
      STORAGE_ID: "minioadmin"
      STORAGE_PASSWORD: "minioadmin"
      REDIS_URL: "redis://redis:6379"
      TEMP_VIDEO_BUCKET: "tempvideo"
      PRODUCTION_BUCKET: "production"
      FRONTEND_URL: "http://localhost"
    depends_on:
      - database
      - redis
      - minio
      - rabbitmq
  frontend:
    build: ./frontend/
    image: skillforgefrontend
    container_name: frontend
    ports:
      - 80:80
    environment:
      VITE_API_URL: "http://localhost:3000"
    depends_on:
      - backend

  database:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  minio:
    build: ./minio/
    image: minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      API_PORT: 9000
      UI_PORT: 9090
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_NOTIFY_AMQP_URL: amqp://guest:guest@rabbitmq:5672
      MINIO_NOTIFY_AMQP_EXCHANGE: minio_exchange
      MINIO_NOTIFY_AMQP_EXCHANGE_TYPE: "fanout"
      MINIO_NOTIFY_AMQP_ROUTING_KEY: minio_routing
      EVENT_BUCKET: tempvideo
      PRODUCTION_BUCKET: production
    volumes:
      - minio_data:/data
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # AMQP port
      - "15672:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq

  videoprocessor:
    build: ./video-processor/
    image: videoprocessor
    container_name: videoprocessor
    environment:
      DATABASE_URL: "postgresql://postgres:12345678@database:5432/skillforge"
      EXCHANGE: "minio_exchange"
      ROUTING_KEY: "minio_routing"
      PRODUCTION_BUCKET: "production"
      STORAGE_SERVER: "http://minio:9000"
      AMQP_URL: "amqp://guest:guest@rabbitmq:5672"
      PUBLIC_STORAGE_URL: "http://localhost:9000"
      STORAGE_ID: "minioadmin"
      STORAGE_PASSWORD: "minioadmin"
    depends_on:
      - minio
      - rabbitmq
      - database

volumes:
  minio_data:
  db_data:
  redis_data:
  rabbitmq_data:
  rabbitmq_logs:
